spring.application.name=product-service
server.port=8082
spring.datasource.url=jdbc:h2:mem:products-db
spring.config.import=optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8085}
aws.s3.endpoint=http://localhost:9000
aws.region=us-east-1
aws.access-key=minioadmin
aws.secret-key=minioadmin
aws.bucket-name=billing-microservice